### ISSUE TITLE
Retain user "interest" selection after selecting person

### ISSUE THREAD

**Issue by matthewfeickert** [AFIDSI/datascience-map#16]
At the moment (6dee9f6cf79cde30d389f9c481ef41f3db091687 or 2024-11-07 &mdash; not sure what is actually deployed) if a user makes a selection on the map (e.g. https://maps.datascience.wisc.edu/open-source/)

![image](https://github.com/user-attachments/assets/6a7b9a5d-5a07-4c69-8386-064e3cf8c6c2)

and then selects a person from the map

![image](https://github.com/user-attachments/assets/d95ace5c-6035-470a-b9f8-ce9b735026f4)

when the user selects the "X" close button on the viewed profile to return to the map

![image](https://github.com/user-attachments/assets/a8bfa8f2-1683-4eb6-a019-f8766096d127)

they are returned to a view with there previous interest selections removed (and reset to the default of "All")

![image](https://github.com/user-attachments/assets/2c041a70-aaec-4d5f-bc8d-c11e0313499e)

This behavior is the opposite of what I would expect, where as a user I would like to have my selections retained until I intentionally decide to reset/remove them.

**Comment by amegahed** [comment]
Interests, appointments, and affiliates checkboxes should all be "remembered" now.   

Note: Interests are not retained after reloading the page and are not captured in the query string when sharing urls.  If those behaviors are desired, that is an additional step.

**Comment by matthewfeickert** [comment]
As no PR was used, this was resolved by the following commits:
* https://github.com/UW-Madison-DSI/community-map/commit/88fc39ce1cdf032aa76ceada7ab0d1fdb99aecb3
* https://github.com/UW-Madison-DSI/community-map/commit/3fbde03a269c90d035e9d2e85dcf6eb5a622e336
